### ISSUE TITLE
question about setting environment variables for a pod

### ISSUE THREAD

**Issue by Matt-Dee** [doriordan/skuber#168]
How do I do this?  I've browsed through the examples and didn't see any

more importantly, I'm trying to do something like...
```
env:
  - name: DATABASE_URL
     valueFrom:
       secretKeyRef:
         name: mariadb-secret
         key: maria.db.url
```
