### ISSUE TITLE
Volume Question

### ISSUE THREAD

**Issue by Matt-Dee** [doriordan/skuber#233]
Looked for an example using volumes.  Is there a way to achieve the following with Volumes.

So a volume mount, that points to a yaml file within a configmap.

```yaml
#apiVersion: extensions/v1beta1
apiVersion: batch/v1
kind: Job
metadata:
  name: argo-run
  labels:
    app: argo-run
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: argo-run
    spec:
      containers:
      - image: cmdaa/cmdaa-workflow:0.0.1
        name: argo-run
        imagePullPolicy: IfNotPresent
        command: [sh, -cx]
        args: ["argo submit /loglikelihood.yaml -p analytic-name=${ANALYTIC_NAME} -p ll-threshold=${LL_THRESHOLD} -p cosine-sim-threshold=${COSINE_THESHOLD}"]
        env:
        - name: ANALYTIC_NAME
          value: "hadoop"
        - name: LL_THRESHOLD
          value: "0.05"
        - name: COSINE_THESHOLD
          value: "0.90"
#        env:
#        - name: ANALYTIC_NAME
#          value: hadoop
#        - name: LL_THRESHOLD
#          value: 0.05
#        - name: COSINE_SIM_THRESHOLD
#          value: 0.90
        volumeMounts:
            - mountPath: /root/.kube
              name: kube-config
      volumes:
        - name: kube-config
          configMap:
             name: kube-config
             items:
              - key: config
                path:  config
      restartPolicy: Never
  backoffLimit: 1
```
