### ISSUE TITLE
Volume Mount

### ISSUE THREAD

**Issue by Matt-Dee** [doriordan/skuber#235]
Trying to achieve the following with skuber...

```
#apiVersion: extensions/v1beta1
apiVersion: batch/v1
kind: Job
metadata:
  name: argo-run
  labels:
    app: argo-run
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: argo-run
    spec:
      containers:
      - image: cmdaa/cmdaa-workflow:0.0.1
        name: argo-run
        imagePullPolicy: IfNotPresent
        command: [sh, -cx]
        args: ["argo submit /loglikelihood.yaml -p analytic-name=${ANALYTIC_NAME} -p ll-threshold=${LL_THRESHOLD} -p cosine-sim-threshold=${COSINE_THESHOLD}"]
        env:
        - name: ANALYTIC_NAME
          value: "hadoop"
        - name: LL_THRESHOLD
          value: "0.05"
        - name: COSINE_THESHOLD
          value: "0.90"
#        env:
#        - name: ANALYTIC_NAME
#          value: hadoop
#        - name: LL_THRESHOLD
#          value: 0.05
#        - name: COSINE_SIM_THRESHOLD
#          value: 0.90
        volumeMounts:
            - mountPath: /root/.kube
              name: kube-config
      volumes:
        - name: kube-config
          configMap:
             name: kube-config
             items:
              - key: config
                path:  config
      restartPolicy: Never
  backoffLimit: 1
```

I have tried the following without success:
```
...
val container = Container(name = "loglikelihood-workflow", image = "cmdaa/cmdaa-workflow:0.0.1", command = List("sh","-xc"), volumeMounts = List( new Volume.Mount(name = "kube-websvc-config", mountPath = "/root/.kube") )).
                  withImagePullPolicy(Container.PullPolicy.Always).
                  withArgs("argo submit /loglikelihood.yaml -p analytic-name=${ANALYTIC_NAME} -p ll-threshold=${LL_THRESHOLD} -p cosine-sim-threshold=${COSINE_THESHOLD}").
                  setEnvVar("ANALYTIC_NAME", analytic).
                  setEnvVar("LL_THRESHOLD", llThreshold).
                  setEnvVar("COSINE_THESHOLD", cosThreshold)

val volume = new Volume( name = "kube-websvc-config", source = Volume.ConfigMapVolumeSource( name = "kube-websvc-config", items = List( new Volume.KeyToPath( key = "config", path = "config" ) ) ) )

val spec = Pod.Spec().addVolume(volume).addContainer(container).withRestartPolicy(RestartPolicy.Never)
val pod = Pod(s"loglikelihood-workflow-${dt}", spec)

val k8s = k8sInit(Configuration.inClusterConfig.get)

Await.result(k8s create pod , Duration.Inf)
...
```
