### ISSUE TITLE
ConfigMap Question

### ISSUE THREAD

**Issue by Matt-Dee** [doriordan/skuber#300]
Hey Dave, 

Do you have an example of saving a configmap into a namespace that contains content like this...

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: default
data:
  config.yaml: |
    namespaces:
      - default
    labels:
      - "app"
      - "owner"
```

**Comment by Matt-Dee** [comment]
I would just assume set the map value to 

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: default
data:
  config.yaml: | <file content on a single line>

**Comment by Matt-Dee** [comment]
Seems to be interpreting my entry as a string.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: default
data:
  config.yaml: "|\n\t\t{\"json\":\"value\"}" 
```
